apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: rollouts-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/axodevelopment/argo-examples.git
    targetRevision: main
    path: rollouts/rollout-bluegreen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true