apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-canary
  labels:
    app: rollouts-demo-canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-demo-canary
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-canary
      trafficRouting:
      steps:
      - setWeight: 20
      - pause: { duration: 20 }
      - setWeight: 40
      - pause: { duration: 20 }
      - setWeight: 60
      - pause: { duration: 20 }
      - setWeight: 80
      - pause: { duration: 10 }
  template:
    metadata:
      labels:
        app: rollouts-demo-canary
    spec:
      containers:
      - name: rollouts-demo-canary
        image: argoproj/rollouts-demo:yellow
        ports:
        - containerPort: 8080
